services:
  - type: web
    name: currency-exchange-api
    runtime: python
    buildCommand: "python database_setup.py"
    startCommand: "python myServer.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0